version: "3.4"

services:
  distancecalculator:
    image: distancecalculator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/usr/src/app/src
      - ./logs:/logs
